name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22999 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SCP
        run: |
          # 1. Runner me se extra files delete karein taaki wo cPanel pe na jayein
          shopt -s dotglob
          rm -rf .git .github etc logs config.php db_config.php mail public_ftp ssl tmp access-logs etc.zip santaclauz_web.zip
          
          # 2. Files ko cPanel ke target folder me bhej dein (Port 22999 ke sath)
          scp -P 22999 -v -q -r * ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/technologymindz.co/
